### ISSUE TITLE
LaTeX support?

### ISSUE THREAD

**Issue by matildepark** [urbit/foundation-design-system#12]

**Comment by ghost** [comment]
[mathjax](https://github.com/mathjax/MathJax) and [katex](https://github.com/KaTeX/KaTeX) seem to be the 2 main latex web renderers. [performance looks about the same](https://www.intmath.com/cg5/katex-mathjax-comparison.php) (slight edge to mathjax 3). from what i've heard, mathjax supports more of the latex language than katex

here's a pretty good post on some of the options: https://danmackinlay.name/notebook/latex_free_mathematics.html
